# script created by KSB, 08.08.18
# Perform DE analysing relationship between islands using RUVs as batch correction method

# load dependencies: libraries, human count data and data preprocessing
source("/Users/katalinabobowik/Documents/UniMelb_PhD/Analysis/UniMelb_Sumba/Scripts/GIT/SEA_Regulatory_Variation/code/Differential_Expression/123_combined/countData_123_combined.R")
source("/Users/katalinabobowik/Documents/UniMelb_PhD/Analysis/UniMelb_Sumba/Scripts/GIT/SEA_Regulatory_Variation/code/Differential_Expression/123_combined/dataPreprocessing_123_combined.R")
source("/Users/katalinabobowik/Documents/UniMelb_PhD/Analysis/UniMelb_Sumba/Scripts/GIT/SEA_Regulatory_Variation/code/batch_effects/RUVs_Setup.R")

# set working directory
setwd("/Users/katalinabobowik/Documents/UniMelb_PhD/Analysis/UniMelb_Sumba/Output/DE_Analysis/123_combined/DE_Island/RUVs")

# setup DGE list object --------------------------------------------------------------------------------------------------

design <- model.matrix(~0 + Island + W_1 + W_2 + W_3 + W_4 + W_5, data=pData(set1))
colnames(design)=gsub("Island", "", colnames(design))
colnames(design)[3]="Mappi"
z <- DGEList(counts=counts(set1), group=Island)
# normalise data with UQ normalisation (as per previous method on seqExpressionSet object)
z <- calcNormFactors(z, method="upperquartile")
# add in genes to the DGEList for downstream use
geneid <- rownames(z)
genes <- select(Homo.sapiens, keys=geneid, columns=c("SYMBOL", "TXCHROM"), keytype="ENSEMBL")
genes <- genes[!duplicated(genes$ENSEMBL),]
z$genes <- genes

# stuff I'm not sure if I need --------------------------------------------------------------

# look at performance of normalisation
# Duplicate data, set normalisation back to 1, and plot difference between normalised and non-normalised data
pdf("NormalisedGeneExpressionDistribution_IndoRNA.pdf", height=15, width=15)
par(oma=c(2,0,0,0), mfrow=c(2,1))
z2 <- z
z2$samples$norm.factors <- 1
lcpm <- cpm(z2, log=TRUE)
boxplot(lcpm, las=2, col=batch.col[as.numeric(batch)], main="", cex.axis=0.75, names=samplenames)
title(main="A. Unnormalised data",ylab="Log-cpm")
z2 <- calcNormFactors(z2, method="upperquartile")
lcpm <- cpm(z2, log=TRUE)
boxplot(lcpm, las=2, col=batch.col[as.numeric(batch)], main="", cex.axis=0.75, names=samplenames)
title(main="B. Normalised data, UpperQuartile",ylab="Log-cpm")
dev.off()

# get density plot after normalisation
pdf("densityPlot_NormalisedGeneExpressionDistribution_IndoRNA.pdf")
plot(density(lcpm[,1]), col=z$samples$batch, lwd=2, ylim=c(0,max(density(lcpm)$y)+.2), las=2, main="", xlab="")
title(main="Filtered data \n Post-Normalisation", xlab="Log-cpm")
abline(v=0, lty=3)
for (i in 2:nsamples){
    den <- density(lcpm[,i])
    lines(den$x, den$y, col=as.numeric(batch)[i], lwd=2)
}
legend("topright", legend=c("First Batch","Second Batch", "Third Batch"), ncol=1, cex=0.8, text.col=unique(as.numeric(batch)), bty="n")
dev.off()

# We can view how UQ normalisation performed using MD plots. This visualizes the library size-adjusted log-fold change between
# two libraries (the difference) against the average log-expression across those libraries (themean). MD plots are generated by comparing sample 1 against an artificial
# library constructed from the average of all other samples. Ideally, the bulk of genes should be centred at a log-fold change of zero.  This indicates
# that any composition bias between libraries has been successfully removed

pdf("MDPlots_UQNormalisation_Outliers.pdf", height=15, width=15)
par(mfrow=c(4,4))
for (i in 1:ncol(z)){
  plotMD(cpm(z, log=TRUE), column=i)
  abline(h=0, col="red", lty=2, lwd=2)
}
dev.off()

# Estimate dispersion. The trend in NB dispersions should decrease smoothly with increasing abundance.  
# This is because the expression of high-abundance genes is expected to be more stable than that of low-abundance genes. 
# Any substantial increase at high abundances may be indicative of batch effects or trended biases.
z <- estimateDisp(z, design, robust=TRUE)
pdf("plotBCV_NBDispersion.pdf")
plotBCV(z)
dev.off()

# Linear modelling --------------------------------------------------------------------------

# set up contrast matrix
contr.matrix <- makeContrasts(SMBvsMTW=Sumba - Mentawai, SMBvsMPI=Sumba - Mappi, MTWvsMPI=Mentawai - Mappi, levels=colnames(design))

# now run voom and see how it performs
pdf("Limma_voom_upperquartilenormalisation.pdf", height=8, width=15)
par(mfrow = c(1,2))
v <- voom(z, design, plot=TRUE)
# fit linear models
vfit <- lmFit(v, design)
vfit <- contrasts.fit(vfit, contrasts=contr.matrix)
efit <- eBayes(vfit)
plotSA(efit, main="Final Model: Mean-variance trend")
dev.off()

# get number of DE genes that pass our theshold and write to file
dt <- decideTests(efit, p.value=0.01, lfc=1)
write.table(summary(dt), file="numberSigDEgenes_RUVs_voom.txt")

# for all contrasts, get names of significant genes
pdf("MDPlot_housekeeping_TopGenes_FDRpval01_LFC01_.pdf", height=15,width=10)
par(mfrow = c(3,1))
for (i in 1:ncol(efit)){
    o <- which(names(efit$Amean) %in% names(which(abs(dt[,i])==1)))
    x <- efit$Amean
    m <- efit$coefficients[,i]
    t=which(names(efit$coefficients[,i]) %in% names(which(abs(dt[,i])==1)))
    G <- z$genes[names(which(abs(dt[,i]))==1),]$SYMBOL
    plotMD(efit, column=i, status=dt[,i], main=colnames(efit)[i], hl.col=c("blue","red"), values=c(-1,1))
    abline(h=c(1,-1), lty=2)
    legend(legend=paste(names(summary(dt)[,i]), summary(dt)[,i], sep="="), x="bottomright", border=F, bty="n")
    text(x[o], m[t], labels=G)
}
dev.off()

# plot log2 fold change between islands
pdf("log2FC_IslandComparisons_pval01.pdf", height=15, width=10)
# note 'p.value' is the cutoff value for adjusted p-values
topTable <- topTable(efit, coef=1, n=Inf, p.value=0.01)
plot(density(topTable$logFC), col=1, xlim=c(-2,2), main="LogFC Density", xlab="LogFC", ylab="Density")
abline(v=c(-1,-0.5,0.5,1), lty=3)
for (i in 2:ncol(efit)){
    topTable <- topTable(efit, coef=i, n=Inf, p.value=0.01)
    lines(density(topTable$logFC), col=i, xlim=c(-2,2))
}
legend(x="topright", bty="n", col=1:ncol(efit), legend=colnames(efit), lty=1, lwd=2)
dev.off()


# We can also look at the top DE genes with a heatmap of logCPM values for the top 100 genes. Each gene (or row) is scaled so that mean expression is zero and the standard deviation is one (we're using 'E' from the voom object which is a numeric matrix of normalized expression values on the log2 scale). Samples with relatively high expression of a given gene are marked in red and samples with relatively low expression are marked in blue. Lighter shades and white represent genes with intermediate expression levels. Samples and genes are reordered by the method of hierarchical clustering
# set up colors
mycol <- colorpanel(1000,"blue","white","red")
colors=c("steelblue","goldenrod1","red2")
cc=colors[Island]
pdf("topGenes_Heatmap.pdf", height=15, width=15)
for (i in 1:ncol(efit)){
    topTable <- topTable(efit, coef=i, p.value=0.01, lfc=1, n=Inf)
    if (nrow(topTable) > 0){
        index <- which(v$genes$ENSEMBL %in% topTable$ENSEMBL[1:100])
        heatmap.2(v$E[index,], scale="row",labRow=v$genes$SYMBOL[index], labCol=Island, col=mycol, trace="none", density.info="none", margin=c(8,6), lhei=c(2,10), dendrogram="column", ColSideColors=cc, keysize=1, cexRow=1.5, main=colnames(efit)[i])
    }
    # write out topTable genes for the whole gene list
    write.table(topTable, file=paste0("topTable_",colnames(efit)[i],".txt"))
    # get what these genes are doing from Biomart and save to file
    sig.Genes <- getBM(attributes = c('ensembl_gene_id', 'external_gene_name', 'description', "interpro","interpro_description"), mart = ensembl.mart.90,values=rownames(topTable), filters="ensembl_gene_id")
    write.table(sig.Genes, file=paste0("significantGenes_RUVs_",colnames(efit)[i],".txt")) 
}
dev.off()

# show the number of DE genes between all islands
pdf("vennDiagram_allSigDEGenes_05FDR.pdf", height=15, width=15)
vennDiagram(dt[,1:3], circle.col=c("red", "blue", "green"))
dev.off()

# get DE genes in common with all islands
de.common <- which(dt[,1]!=0 & dt[,2]!=0 & dt[,3]!=0)

# find out what these genes are doing
commonGenes.results <- getBM(attributes = c('ensembl_gene_id', 'external_gene_name', 'description', "interpro","interpro_description"), mart = ensembl.mart.90,values=names(de.common), filters="ensembl_gene_id")
write.table(commonGenes.results, file="allCommonGenes.txt")

# get which genes are in common between populations with mappi (i.e., SMBvsMPI and MTWvsMPI)
de.common.MPI <- which(dt[,2]!=0 & dt[,3]!=0)

# find out what these genes are doing
commonGenes.MPI <- getBM(attributes = c('ensembl_gene_id', 'external_gene_name', 'description', "interpro","interpro_description"), mart = ensembl.mart.90,values=names(de.common.MPI), filters="ensembl_gene_id")
write.table(commonGenes.MPI, file="allCommonGenes_MPI.txt")

# Let's see how the expression levels of each of our significant genes are distributed within each island. First, assign our top genes and ensembl IDs to variables
topGenes=c("MARCO", "SIGLEC6", "SIGLEC7","SIGLEC14", "KLRF1", "IFI27", "RNF182", "MDGA1", "UTS2", "MYOM2", "LOC102724159")
topEnsembl=c("ENSG00000019169", "ENSG00000105492", "ENSG00000168995", "ENSG00000254415","ENSG00000150045", "ENSG00000165949", "ENSG00000180537", "ENSG00000112139", "ENSG00000049247", "ENSG00000036448", "ENSG00000275464")

# To visualise distributions, we'll be making violin plots using ggpubr which needs p-value labels. Let's go ahead and make a matrix to input this into ggpubr
# first set up matrix
topGenes.pvalue=matrix(nrow=length(topEnsembl), ncol=ncol(efit))
rownames(topGenes.pvalue)=topEnsembl
colnames(topGenes.pvalue)=colnames(efit)
for (i in 1:ncol(efit)){
    # get significant genes over a logFC of 1 for all Island comparisons
    topTable <- topTable(efit, coef=i, p.value=0.01, lfc=1, n=Inf)
    for(j in topEnsembl){
        # input the adjusted p.value for each gene
        topGenes.pvalue[j,i]=topTable[j,"adj.P.Val"]
    }
}

# make pvalues into scientific notation with max 3 digits
topGenes.pvalue=formatC(topGenes.pvalue, format="e", digits=2, drop0trailing=T)
# convert e notation to base 10 notation
topGenes.pvalue=sub("e", "x10^", topGenes.pvalue)

# finally, let's make the violin plots using fancy ggpubr
pdf("TopGenes_ggboxplot_Island.pdf", height=8, width=10)
counter=0
for(ensembl in topEnsembl){
    counter=counter+1
    gene.df <- data.frame(cpm(z$counts[which(z$genes$ENSEMBL==ensembl),],log=T),Island)
    colnames(gene.df)=c("CPM", "Island")
    annotation_df <- data.frame(start=c("Sumba","Sumba", "Mentawai"), end=c("Mentawai","West Papua","West Papua"), y=c(max(gene.df[,1]+4),max(gene.df[,1]+5),max(gene.df[,1]+6)), label=paste("limma p-value =",topGenes.pvalue[ensembl,],sep=" "))
    print(ggviolin(gene.df, x = "Island", y = "CPM", fill="Island", add=c("jitter","boxplot"), main=topGenes[counter], palette=1:3, add.params = c(list(fill = "white"), list(width=0.05))) + geom_signif(data=annotation_df,aes(xmin=start, xmax=end, annotations=label, y_position=y),textsize = 5, vjust = -0.2,manual=TRUE) + ylim(NA, max(gene.df[,1])+7))
}
dev.off()


# Enrichment analysis for Gene Ontology ----------------------------------------------------------------------------------------------------

# transform ensembl IDs to entrez IDs to be compatible with human c2 dataset (below)
ensembl_genes=rownames(z)
entrez=getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id", "entrezgene", "description"),values= ensembl_genes,mart=ensembl.mart.90)
z$entrezID=entrez[match(rownames(z), entrez[,1]), 2]

# gene set testing with Camera
load(url("http://bioinf.wehi.edu.au/software/MSigDB/human_c2_v5p2.rdata")) 
idx <- ids2indices(Hs.c2,id=z$entrezID) 
for (i in 1:ncol(contr.matrix)){
    camera.matrix=camera(v,idx,design,contrast=contr.matrix[,i])
    write.table(camera.matrix, file=paste0("cameraMatrix_",colnames(contr.matrix)[i],".txt"))
}

# gene set testing with goSeq
for(pop in 1:ncol(efit)){
    for(pval in c(0.05, 0.01)){
        topTable <- topTable(efit, coef=pop, n=Inf, p.value=pval, lfc=1)
        gene.vector=as.integer(rownames(z) %in% rownames(topTable))
        names(gene.vector)=rownames(z)

        # set the probability weighting fcuntion, i.e., implement a weight for each gene dependent on its length
        pwf=nullp(gene.vector,"hg19","ensGene")
        # use  the  default  method  to  calculate  the  over  and  under  expressed  GO categories among DE genes
        GO.wall=goseq(pwf,"hg19","ensGene",use_genes_without_cat=TRUE)

        # now let's interpret the results. First we need to apply a multiple hypothesis testing correction set at 5% (BH method)
        enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue, method="BH")<.05,]
        write.table(enriched.GO, file=paste("enrichedGOterms",colnames(efit)[pop],pval,".txt", sep="_"), quote=F, row.names=F)
        if(nrow(enriched.GO)>0){
            zz=file(paste("topTen_enrichedGOterms",pop,pval,".txt", sep="_"), open="wt")
            sink(zz)
            sink(zz, type = "message")
            # get GO terms for top ten enriched GO terms - write output with the sink() function
            for(go in 1:length(enriched.GO$category)){
                print(GOTERM[[enriched.GO$category[go]]])
            }
        }
        sink(type = "message")
        sink()

        # KEGG pathway analysis
        en2eg=as.list(org.Hs.egENSEMBL2EG)
        # Get the mapping from Entrez 2 KEGG
        eg2kegg=as.list(org.Hs.egPATH)
        # Define a function which gets all unique KEGG IDs
        # associated with a set of Entrez IDs
        grepKEGG=function(id,mapkeys){unique(unlist(mapkeys[id],use.names=FALSE))}
        # Apply this function to every entry in the mapping from
        # ENSEMBL 2 Entrez to combine the two maps
        kegg=lapply(en2eg,grepKEGG,eg2kegg)

        # produce PWF as before
        pwf=nullp(gene.vector,"hg19","ensGene")
        KEGG=goseq(pwf,gene2cat=kegg, use_genes_without_cat=TRUE)
        enriched.GO.kegg=KEGG[p.adjust(KEGG$over_represented_pvalue, method="BH")<.05,]
        write.table(enriched.GO.kegg, file=paste("enrichedGOkegg",pop,pval,".txt", sep="_"))
    }
}

# Enrichment Visualisation ----------------------------------------------------------------------------------------------------


# Having played around with many visualisation options, it seems as though using Revigo is the best and most user-friendly. Using the output from the GoSeq enriched Go results (FDR <0.05), we can plug our GO IDs into Revigo (http://revigo.irb.hr/) and then output this as an R script.
# First save  output (remember that SMBvsMTW has no significantly enriched GO pathways so we'll only do this for SMBvsMPI and MTWvsMPI)  

# Revigo for MTW vs MPI (pval of 0.05 FDR)- Treemap
source("/Users/katalinabobowik/Documents/UniMelb_PhD/Analysis/UniMelb_Sumba/Scripts/GIT/SEA_RegulatoryVariation/code/Differential_Expression/123_combined/REVIGO_MTWvsMPI_Treemap.r")
# scatterplot
source("/Users/katalinabobowik/Documents/UniMelb_PhD/Analysis/UniMelb_Sumba/Scripts/GIT/SEA_RegulatoryVariation/code/Differential_Expression/123_combined/REVIGO_MTWvsMPI_Scatterplot.r")

# Revigo for SMB vs MPI (pval of 0.05 FDR)- Treemap
source("/Users/katalinabobowik/Documents/UniMelb_PhD/Analysis/UniMelb_Sumba/Scripts/GIT/SEA_RegulatoryVariation/code/Differential_Expression/123_combined/REVIGO_SMBvsMPI_Treemap.r")
# scatterplot
source("/Users/katalinabobowik/Documents/UniMelb_PhD/Analysis/UniMelb_Sumba/Scripts/GIT/SEA_RegulatoryVariation/code/Differential_Expression/123_combined/REVIGO_SMBvsMPI_Scatterplot.r")

# Reactome --------------------------------------------------
# get what the top genes are doing from Reactome
for (i in 1:ncol(efit)){
    topTable <- topTable(efit, coef=i, p.value=0.01, lfc=1, n=Inf)
    entrez=getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id", "entrezgene"),values= rownames(topTable),mart=ensembl.mart.90)
    de <- entrez[,2]
    x <- enrichPathway(gene=de,pvalueCutoff=0.05, readable=T)
    if(nrow(x) > 0){
        pdf(paste0("enriched_pathways_reactome_",colnames(efit)[i],"PopComparisons.pdf"), height=5, width=10)
        print(barplot(x, showCategory=nrow(x), font.size = 8, title = colnames(efit)[i]))
        dev.off()
    }
}

writeLines(capture.output(sessionInfo()), "sessionInfo.txt")
