# script created by KSB, 08.08.18
# Perform DE analysing relationship between islands

### Last edit: IGR 2019.10.19
### Changed paths to deal with removal of MPI-296

### 0. Load dependencies and functions and set input paths ###
### 1. Begin analyses and initial QC ###
### 2. DE testing with duplicate correlation and blocking ###
### 3. DE testing without duplicate correlation ###
### 4. Visual QC of duplicate correlation voom output after fitting linear models ###
### 5. Summary and visualisation of gene trends ###

### TO DO:
### Fix everything that's commented out (just figures)


##############################################################
### 0. Load dependencies and functions and set input paths ###
##############################################################

# Load dependencies:
library(edgeR)
library(plyr)
library(NineteenEightyR)
library(RColorBrewer)
library(ggplot2)
library(ggsignif)
library(viridis)
library(circlize)
library(ComplexHeatmap)
library(wesanderson)

# Set paths:
inputdir <- "/data/cephfs/punim0586/igallego/indoRNA/de_testing/no_mpi296/" # on server
covariatedir <- "/data/cephfs/punim0586/igallego/indoRNA/"

# Set output directory and create it if it does not exist:
outputdir <- "/data/cephfs/punim0586/igallego/indoRNA/de_testing/no_mpi296/"
edaoutput <- paste0(outputdir, "/eda/")

if (file.exists(outputdir) == FALSE){
    dir.create(outputdir, recursive=T)
    dir.create(edaoutput, recursive=T)
}

# Load colour schemes:
#Colour schemes:
korowai <- wes_palette("Zissou1", 20, type = "continuous")[20]
mentawai <- wes_palette("Zissou1", 20, type = "continuous")[1]
sumba <- wes_palette("Zissou1", 20, type = "continuous")[11]

smb_mtw <- wes_palette("Darjeeling1", 9, type = "continuous")[3]
smb_kor <- wes_palette("Darjeeling1", 9, type = "continuous")[7]
mtw_kor <- "darkorchid4"
# set up colour palette for batch
batch.col=electronic_night(n=3)


# Load log CPM matrix and y object:
# lcpm
load(paste0(inputdir, "indoRNA.logCPM.TMM.filtered.Rda"))
# y DGE list object
load(paste0(inputdir, "indoRNA.read_counts.TMM.filtered.Rda"))


########################################
### 1. Begin analyses and initial QC ###
########################################

# We don't know what the age is for SMB-PTB028 (#116) so we will just add in the median age of Sumba (44.5)
yFilt$samples$Age[which(is.na(yFilt$samples$Age) == T)]=45

# Set up design matrix
design <- model.matrix(~0 + yFilt$samples$Island + yFilt$samples$Age + yFilt$samples$batch + yFilt$samples$RIN + yFilt$samples$CD8T + yFilt$samples$CD4T + yFilt$samples$NK + yFilt$samples$Bcell + yFilt$samples$Mono + yFilt$samples$Gran)
colnames(design)=gsub("Island", "", colnames(design))

# rename columns to exclude spaces and unrecognised characters
colnames(design)=gsub("yFilt\\$samples\\$", "", colnames(design))
colnames(design)=gsub("West Papua", "West_Papua", colnames(design))

# Rename Mappi to Korowai for downstream processing:
yFilt$samples$Sampling.Site <- gsub("Mappi", "Korowai", yFilt$samples$Sampling.Site)

# set up contrast matrix
contr.matrix <- makeContrasts(SMBvsMTW=Sumba - Mentawai, SMBvsKOR=Sumba - West_Papua, MTWvsKOR=Mentawai - West_Papua, levels=colnames(design))

yFilt <- calcNormFactors(yFilt, method="TMM")

# We can view how TMM normalisation performed using MD plots. This visualizes the library size-adjusted log-fold change between
# two libraries (the difference) against the average log-expression across those libraries (themean). MD plots are generated by comparing sample 1 against an artificial
# library constructed from the average of all other samples. Ideally, the bulk of genes should be centred at a log-fold change of zero.  This indicates
# that any composition bias between libraries has been successfully removed
# pdf(paste0(outputdir,"MDPlots_TMM_Normalisation_OutliersCheck.pdf"), height=15, width=15)
# par(mfrow=c(4,4))
# for (i in 1:ncol(yFilt)){
#   plotMD(cpm(yFilt, log=TRUE), column=i)
#   abline(h=0, col="red", lty=2, lwd=2)
# }
# dev.off()

#############################################################
### 2. DE testing with duplicate correlation and blocking ###
#############################################################

# create a new variable for blocking using sample IDs
yFilt$samples$ind <- sapply(strsplit(as.character(yFilt$samples$samples), "[_.]"), `[`, 1)

# First, we need to perform voom normalisation

# No normalisation between samples beyond tmm and voom:
    voomNoNorm <- voom(yFilt, design, normalize.method="none", plot=F) 
    dupcorNone <- duplicateCorrelation(voomNoNorm, design, block=yFilt$samples$ind) # 23 or more non-convergences
    # The value dupcor$consensus estimates the average correlation within the blocks and should be positive
    dupcorNone$consensus # sanity check
    # [1] 0.6796663
    median(voomNoNorm$weights) # another sanity check:
    # [1] 22.8338
    save(voomNoNorm, file=paste0(outputdir, "voomNoNorm.tmm.filtered.indoRNA.Rda"))

    # Second round:
    voomNoNormDup <- voom(yFilt, design, plot=TRUE, block=yFilt$samples$ind, correlation=dupcorNone$consensus)
    dupcorNoneDup <- duplicateCorrelation(voomNoNormDup, design, block=yFilt$samples$ind) # 24 non convergences
    dupcorNoneDup$consensus # sanity check pt 2
    # [1] 0.6796721
    median(voomNoNormDup$weights) # another sanity check, pt 2 
    # [1] 22.41583

    pdf(file=paste0(edaoutput, "voomNoNorm.tmm.filtered.indoRNA.densities.pdf"))
        plotDensities(voomNoNormDup, group=yFilt$samples$batch)
        plotDensities(voomNoNormDup, group=yFilt$samples$Island)
    dev.off()
    save(voomNoNormDup, file=paste0(outputdir, "voomNoNorm.tmm.filtered.duplicate_corrected.indoRNA.Rda"))

    # DE testing:
    # the inter-subject correlation is input into the linear model fit
    voomNoNormDupVfit <- lmFit(voomNoNormDup, design, block=yFilt$samples$ind, correlation=dupcorNoneDup$consensus)
    voomNoNormDupVfit <- contrasts.fit(voomNoNormDupVfit, contrasts=contr.matrix)
    voomNoNormDupEfit <- eBayes(voomNoNormDupVfit, robust=T)

    pdf(file=paste0(edaoutput, "voomNoNorm.tmm.filtered.indoRNA.mean-variance-trend.pdf"))
        plotSA(voomNoNormDupEfit, main="Mean-variance trend elimination with duplicate correction")
    dev.off()

    # get top genes using toptable
    voomNoNormDupTopTableSMB.MTW <- topTable(voomNoNormDupEfit, coef=1, n=Inf, sort.by="p")
    voomNoNormDupTopTableSMB.KOR <- topTable(voomNoNormDupEfit, coef=2, n=Inf, sort.by="p")
    voomNoNormDupTopTableMTW.KOR <- topTable(voomNoNormDupEfit, coef=3, n=Inf, sort.by="p")

# Quantile normalisation between samples and tmm and voom:
    voomQuant <- voom(yFilt, design, normalize.method="quantile", plot=F) 
    dupcorQuant <- duplicateCorrelation(voomQuant, design, block=yFilt$samples$ind) # 46 warnings
    # The value dupcor$consensus estimates the average correlation within the blocks and should be positive
    dupcorQuant$consensus # sanity check
    # [1] 0.6888087
    median(voomQuant$weights) # another sanity check:
    # [1] 22.94226
    save(voomQuant, file=paste0(outputdir, "voomQuant.tmm.filtered.indoRNA.Rda"))

    # Second round:
    voomQuantDup <- voom(yFilt, design, plot=TRUE, block=yFilt$samples$ind, correlation=dupcorQuant$consensus)
    dupcorQuantDup <- duplicateCorrelation(voomQuantDup, design, block=yFilt$samples$ind) # 48 warnings
    dupcorQuantDup$consensus # sanity check pt 2
    # [1] 0.6796766
    median(voomQuantDup$weights) # another sanity check, pt 2 
    # [1] 22.37909

    pdf(file=paste0(edaoutput, "voomQuant.tmm.filtered.indoRNA.densities.pdf"))
        plotDensities(voomQuantDup, group=yFilt$samples$batch)
        plotDensities(voomQuantDup, group=yFilt$samples$Island)
    dev.off()
    save(voomQuantDup, file=paste0(outputdir, "voomQuant.tmm.filtered.duplicate_corrected.indoRNA.Rda"))

    # DE testing:
    # the inter-subject correlation is input into the linear model fit
    voomQuantDupVfit <- lmFit(voomQuantDup, design, block=yFilt$samples$ind, correlation=dupcorQuantDup$consensus)
    voomQuantDupVfit <- contrasts.fit(voomQuantDupVfit, contrasts=contr.matrix)
    voomQuantDupEfit <- eBayes(voomQuantDupVfit, robust=T)

    pdf(file=paste0(edaoutput, "voomQuant.tmm.filtered.indoRNA.mean-variance-trend.pdf"))
        plotSA(voomQuantDupEfit, main="Mean-variance trend elimination with duplicate correction")
    dev.off()

    # get top genes using toptable
    voomQuantDupTopTableSMB.MTW <- topTable(voomQuantDupEfit, coef=1, n=Inf, sort.by="p")
    voomQuantDupTopTableSMB.KOR <- topTable(voomQuantDupEfit, coef=2, n=Inf, sort.by="p")
    voomQuantDupTopTableMTW.KOR <- topTable(voomQuantDupEfit, coef=3, n=Inf, sort.by="p")


# Loess normalisation between samples and tmm and voom:
    voomLoess <- voom(yFilt, design, normalize.method="cyclicloess", plot=F) 
    dupcorLoess <- duplicateCorrelation(voomLoess, design, block=yFilt$samples$ind) # 46 warnings
    # The value dupcor$consensus estimates the average correlation within the blocks and should be positive
    dupcorLoess$consensus # sanity check
    # [1] 0.6825221
    median(voomLoess$weights) # another sanity check:
    # [1] 23.18414
    save(voomLoess, file=paste0(outputdir, "voomLoess.tmm.filtered.indoRNA.Rda"))

    # Second round:
    voomLoessDup <- voom(yFilt, design, plot=TRUE, block=yFilt$samples$ind, correlation=dupcorLoess$consensus)
    dupcorLoessDup <- duplicateCorrelation(voomLoessDup, design, block=yFilt$samples$ind) # 48 warnings
    dupcorLoessDup$consensus # sanity check pt 2
    # [1] 0.6796738
    median(voomLoessDup$weights) # another sanity check, pt 2 
    # [1] 22.40257

    pdf(file=paste0(edaoutput, "voomLoess.tmm.filtered.indoRNA.densities.pdf"))
        plotDensities(voomLoessDup, group=yFilt$samples$batch)
        plotDensities(voomLoessDup, group=yFilt$samples$Island)
    dev.off()
    save(voomLoessDup, file=paste0(outputdir, "voomLoess.tmm.filtered.duplicate_corrected.indoRNA.Rda"))

    # DE testing:
    # the inter-subject correlation is input into the linear model fit
    voomLoessDupVfit <- lmFit(voomLoessDup, design, block=yFilt$samples$ind, correlation=dupcorLoessDup$consensus)
    voomLoessDupVfit <- contrasts.fit(voomLoessDupVfit, contrasts=contr.matrix)
    voomLoessDupEfit <- eBayes(voomLoessDupVfit, robust=T)

    pdf(file=paste0(edaoutput, "voomLoess.tmm.filtered.indoRNA.mean-variance-trend.pdf"))
        plotSA(voomLoessDupEfit, main="Mean-variance trend elimination with duplicate correction")
    dev.off()

    # get top genes using toptable
    voomLoessDupTopTableSMB.MTW <- topTable(voomLoessDupEfit, coef=1, n=Inf, sort.by="p")
    voomLoessDupTopTableSMB.KOR <- topTable(voomLoessDupEfit, coef=2, n=Inf, sort.by="p")
    voomLoessDupTopTableMTW.KOR <- topTable(voomLoessDupEfit, coef=3, n=Inf, sort.by="p")

# LOL omg what was the point? On the basis of this, going with no norm so there's no need to think about it any deeper.
summary(decideTests(voomNoNormDupEfit, method="separate", adjust.method = "BH", p.value = 0.01))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down        898     2325     2102
# NotSig    11430     8479     8887
# Up          647     2171     1986
summary(decideTests(voomQuantDupEfit, method="separate", adjust.method = "BH", p.value = 0.01))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down        896     2324     2102
# NotSig    11432     8480     8887
# Up          647     2171     1986
summary(decideTests(voomLoessDupEfit, method="separate", adjust.method = "BH", p.value = 0.01))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down        898     2325     2102
# NotSig    11430     8479     8887
# Up          647     2171     1986

summary(decideTests(voomNoNormDupEfit, method="separate", adjust.method = "BH", p.value = 0.01, lfc=0.5))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down         96      606      536
# NotSig    12661    11577    11958
# Up          218      792      481
summary(decideTests(voomQuantDupEfit, method="separate", adjust.method = "BH", p.value = 0.01, lfc=0.5))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down         96      606      536
# NotSig    12661    11577    11958
# Up          218      792      481
summary(decideTests(voomLoessDupEfit, method="separate", adjust.method = "BH", p.value = 0.01, lfc=0.5))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down         96      606      536
# NotSig    12661    11577    11958
# Up          218      792      481

summary(decideTests(voomNoNormDupEfit, method="separate", adjust.method = "BH", p.value = 0.01, lfc=1))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down          6       87       96
# NotSig    12940    12662    12748
# Up           29      226      131
summary(decideTests(voomQuantDupEfit, method="separate", adjust.method = "BH", p.value = 0.01, lfc=1))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down          6       87       96
# NotSig    12940    12662    12748
# Up           29      226      131
summary(decideTests(voomLoessDupEfit, method="separate", adjust.method = "BH", p.value = 0.01, lfc=1))
#        SMBvsMTW SMBvsKOR MTWvsKOR
# Down          6       87       96
# NotSig    12940    12662    12748
# Up           29      226      131

write.table(voomNoNormDupTopTableSMB.MTW, file=paste0(outputdir,"topTable.voomNoNorm.tmm.filtered.dup_corrected.SMB-MTW.txt"))
write.table(voomNoNormDupTopTableSMB.KOR, file=paste0(outputdir,"topTable.voomNoNorm.tmm.filtered.dup_corrected.SMB-KOR.txt"))
write.table(voomNoNormDupTopTableMTW.KOR, file=paste0(outputdir,"topTable.voomNoNorm.tmm.filtered.dup_corrected.MTW-KOR.txt"))

# For easily combining with the villages:
save(voomNoNormDupEfit, file=paste0(outputdir, "voomNoNorm.tmm.filtered.dup_corrected.Efit_object.Rda"))

###################################################
### 3. DE testing without duplicate correlation ###
###################################################

### Only doing the nonorm one, because why bother with the others?

    voomNoNormVfit <- lmFit(voomNoNorm, design)
    voomNoNormVfit <- contrasts.fit(voomNoNormVfit, contrasts=contr.matrix)
    voomNoNormEfit <- eBayes(voomNoNormVfit, robust=T)

pdf(file=paste0(edaoutput, "voomNoNorm.tmm.filtered.indoRNA.no_dup_correction.mean-variance-trend.pdf"))
    plotSA(voomNoNormEfit, main="Mean-variance trend elimination without duplicate correction")
dev.off()

# get top genes using toptable
topTableSMB.MTW <- topTable(voomNoNormEfit, coef=1, n=Inf, sort.by="p")
topTableSMB.KOR <- topTable(voomNoNormEfit, coef=2, n=Inf, sort.by="p")
topTableMTW.KOR <- topTable(voomNoNormEfit, coef=3, n=Inf, sort.by="p")

# no LFC threshold
summary(decideTests(voomNoNormEfit, method="separate", adjust.method = "BH", p.value = 0.01))
#       SMBvsMTW SMBvsKOR MTWvsKOR
#Down       1032     2569     2228
#NotSig    11183     8106     8669
#Up          760     2300     2078

# LFC of 0.05
summary(decideTests(voomNoNormEfit, method="separate", adjust.method = "BH", p.value = 0.01, lfc=0.5))
#       SMBvsMTW SMBvsKOR MTWvsKOR
#Down        112      654      558
#NotSig    12603    11492    11920
#Up          260      829      497

# LFC of 1
summary(decideTests(voomNoNormEfit, method="separate", adjust.method = "BH", p.value = 0.01, lfc=1))
#       SMBvsMTW SMBvsKOR MTWvsKOR
#Down          6       93      103
#NotSig    12923    12643    12737
#Up           46      239      135

# Let's check the correlation between those two approaches - sort by gene first, then cor test on adjusted p-value
MTW.KOR <- join(voomNoNormDupTopTableMTW.KOR, topTableMTW.KOR, by="genes")
cor(MTW.KOR[,6], MTW.KOR[,12], method="spearman"    )
# [1] 0.9884076

SMB.KOR <- join(voomNoNormDupTopTableSMB.KOR, topTableSMB.KOR, by="genes")
cor(SMB.KOR[,6], SMB.KOR[,12], method="spearman", use="complete")
# [1] 0.9771854

SMB.MTW <- join(voomNoNormDupTopTableSMB.MTW, topTableSMB.MTW, by="genes")
cor(SMB.MTW[,6], SMB.MTW[,12], method="spearman", use="complete")
# [1] 0.955927

write.table(topTableSMB.MTW, file=paste0(outputdir,"topTable.voomNoNorm.tmm.filtered.not_dup_corrected.SMB-MTW.txt"))
write.table(topTableSMB.KOR, file=paste0(outputdir,"topTable.voomNoNorm.tmm.filtered.not_dup_corrected.SMB-KOR.txt"))
write.table(topTableMTW.KOR, file=paste0(outputdir,"topTable.voomNoNorm.tmm.filtered.not_dup_corrected.MTW-KOR.txt"))


#####################################################################################
### 4. Visual QC of duplicate correlation voom output after fitting linear models ###
#####################################################################################

# check to see p-value distribution is normal
pdf(paste0(edaoutput,"PvalueDist_NotAdjusted_dupCor.pdf"), height=15, width=10)
    par(mfrow=c(3,1))
    for (i in 1:ncol(voomNoNormDupEfit)){
        hist(voomNoNormDupEfit$p.value[,i], main=colnames(voomNoNormDupEfit)[i], ylim=c(0,max(table(round(voomNoNormDupEfit$p.value[,i], 1)))+1000), xlab="p-value")
    }
dev.off()

# check p-value distribution for adjusted p-values
pdf(paste0(edaoutput,"PvalueDist_Adjusted_dupCor.pdf"), height=15, width=10)
    par(mfrow=c(3,1))
    for (i in 1:ncol(voomNoNormDupEfit)){
        topTable <- topTable(voomNoNormDupEfit, coef=i, n=Inf)
        histData <- hist(topTable$adj.P.Val, main=colnames(voomNoNormDupEfit)[i], xlab="p-value")
        hist(topTable$adj.P.Val, main=colnames(voomNoNormDupEfit)[i], ylim=c(0,max(histData$counts)+1000), xlab="p-value")
    }
dev.off()


###################################################
### 5. Summary and visualisation of gene trends ###
###################################################

# plot log2 fold change between islands
pdf(paste0(edaoutput,"log2FC_IslandComparisons_pval01_dupCor.pdf"))
# note 'p.value' is the cutoff value for adjusted p-values
    topTable <- topTable(voomNoNormDupEfit, coef=1, n=Inf, p.value=0.01)
    plot(density(topTable$logFC), col=9, xlim=c(-2,2), main="LogFC Density", xlab="LogFC", ylab="Density", lwd=3)
    abline(v=c(-1,-0.5,0.5,1), lty=3)
    counter=0
    for (i in 2:ncol(voomNoNormDupEfit)){
        counter=counter+1
        topTable <- topTable(voomNoNormDupEfit, coef=i, n=Inf, p.value=0.01)
        lines(density(topTable$logFC), col=9+counter, xlim=c(-2,2), lwd=3)
    }
    legend(x="topright", bty="n", col=9:11, legend=colnames(voomNoNormDupEfit), lty=1, lwd=2)
dev.off()

# graphical representation of DE results through MD plot
pdf(paste0(edaoutput,"MD_Plots_pval01_lfc1_dupCor.pdf"))
    plotMD(voomNoNormDupEfit, column = 1, array = NULL, xlab = "Average log-expression", ylab = "Expression log-ratio",
       main = colnames(voomNoNormDupEfit)[1], status=voomNoNormDupEfit$genes$Status, zero.weights = FALSE)
    abline(h=c(-1,-0.5,0.5,1), lty=3)
    plotMD(voomNoNormDupEfit, column = 2, array = NULL, xlab = "Average log-expression", ylab = "Expression log-ratio",
       main = colnames(voomNoNormDupEfit)[2], status=voomNoNormDupEfit$genes$Status, zero.weights = FALSE)
    abline(h=c(-1,-0.5,0.5,1), lty=3)
    plotMD(voomNoNormDupEfit, column = 3, array = NULL, xlab = "Average log-expression", ylab = "Expression log-ratio",
       main = colnames(voomNoNormDupEfit)[3], status=voomNoNormDupEfit$genes$Status, zero.weights = FALSE)
    abline(h=c(-1,-0.5,0.5,1), lty=3)
dev.off()

# We can also look at the top ten DE genes with a heatmap of logCPM values for the top 100 genes. Each gene (or row) is scaled so that mean expression is zero and the standard deviation is one (we're using 'E' from the voom object which is a numeric matrix of normalized expression values on the log2 scale). Samples with relatively high expression of a given gene are marked in red and samples with relatively low expression are marked in blue. Lighter shades and white represent genes with intermediate expression levels. Samples and genes are reordered by the method of hierarchical clustering

# # We can also make individual pdfs of the top genes
# island1 <- c("Sumba","Mentawai","West Papua")
# island2 <- c("Sumba","Mentawai","West Papua")

# counter <- 0

# for (i1 in island1){
#     island2=island2[-1]
#     for (i2 in island2){
#         counter=counter+1
#         topTable <- topTable(voomNoNormDupEfit, coef=counter, p.value=0.01, lfc=1, n=Inf, sort.by="p")
#         index <- which(vDup$genes$ENSEMBL %in% topTable$ENSEMBL[1:10])
#         df=data.frame(island = as.character(Island[grep(paste(i1,i2,sep="|"), Island)]))
#         ha =  HeatmapAnnotation(df = df, col = list(island = c("Mentawai" =  1, "Sumba" = 2, "West Papua" = 3)))
#         pdf(paste0(outputdir,"HeatmapTopeGenes_",i1,"_vs_",i2,"_dupCor.pdf"), height=10, width=15)
#         draw(Heatmap(t(scale(t(vDup$E[index,])))[,grep(paste(i1,i2,sep="|"), Island)], col=col_fun, column_title = colnames(voomNoNormDupEfit)[counter], top_annotation = ha, show_row_names = T, show_heatmap_legend = T, show_column_names = F, name = "Z-Score"),show_annotation_legend = TRUE,newpage=F)
#         dev.off()
#     }
# }


# # Some Venn diagrams
make.venn.triple(voomNoNormDupTopTableSMB.MTW[voomNoNormDupTopTableSMB.MTW$adj.P.Val <= 0.01,]$genes, voomNoNormDupTopTableSMB.KOR[voomNoNormDupTopTableSMB.KOR$adj.P.Val <= 0.01,]$genes, voomNoNormDupTopTableMTW.KOR[voomNoNormDupTopTableMTW.KOR$adj.P.Val <= 0.01,]$genes, paste0(edaoutput, "all_islands.fdr_0.01"), "Sumba vs\nMentawai", "Sumba vs\nKorowai", "Mentawai\nvs Korowai", voomNoNormDupTopTableSMB.MTW)

make.venn.triple(voomNoNormDupTopTableSMB.MTW[voomNoNormDupTopTableSMB.MTW$adj.P.Val <= 0.01 & abs(voomNoNormDupTopTableSMB.MTW$logFC)>= 0.5,]$genes, voomNoNormDupTopTableSMB.KOR[voomNoNormDupTopTableSMB.KOR$adj.P.Val <= 0.01 & abs(voomNoNormDupTopTableSMB.KOR$logFC)>= 0.5,]$genes, voomNoNormDupTopTableMTW.KOR[voomNoNormDupTopTableMTW.KOR$adj.P.Val <= 0.01 & abs(voomNoNormDupTopTableMTW.KOR$logFC)>= 0.5,]$genes, paste0(edaoutput, "all_islands.fdr_0.01.logfc_0.5"), "Sumba vs\nMentawai", "Sumba vs\nKorowai", "Mentawai\nvs Korowai", voomNoNormDupTopTableSMB.MTW)

make.venn.triple(voomNoNormDupTopTableSMB.MTW[voomNoNormDupTopTableSMB.MTW$adj.P.Val <= 0.01 & abs(voomNoNormDupTopTableSMB.MTW$logFC)>= 1,]$genes, voomNoNormDupTopTableSMB.KOR[voomNoNormDupTopTableSMB.KOR$adj.P.Val <= 0.01 & abs(voomNoNormDupTopTableSMB.KOR$logFC)>= 1,]$genes, voomNoNormDupTopTableMTW.KOR[voomNoNormDupTopTableMTW.KOR$adj.P.Val <= 0.01 & abs(voomNoNormDupTopTableMTW.KOR$logFC)>= 1,]$genes, paste0(edaoutput, "all_islands.fdr_0.01.logfc_1"), "Sumba vs\nMentawai", "Sumba vs\nKorowai", "Mentawai\nvs Korowai", voomNoNormDupTopTableSMB.MTW)


# get DE genes in common with populations compared to Korowai, i.e., SMBvsKOR and MTWvsKOR (since we think this is an interesting island comparison)
allGenes <- merge(voomNoNormDupTopTableSMB.MTW, voomNoNormDupTopTableSMB.KOR, by.x="genes", by.y="genes", suffixes=c(".SMB.MTW", ".SMB.KOR"))
allGenes <- merge(allGenes, voomNoNormDupTopTableMTW.KOR, by.x="genes", by.y="genes")
names(allGenes)[13:19] <- paste0(names(allGenes)[13:19], ".MTW.KOR")

deSummaryAll <- decideTests(voomNoNormDupEfit, p.value=0.01)
deSummary05 <- decideTests(voomNoNormDupEfit, p.value=0.01, lfc=0.5)
deSummary1 <- decideTests(voomNoNormDupEfit, p.value=0.01, lfc=1)

deCommonKOR = which(deSummaryAll[,2]!=0 & deSummaryAll[,3]!=0)
deCommonKOR05 = which(deSummary05[,2]!=0 & deSummary05[,3]!=0)
deCommonKOR1 = which(deSummary1[,2]!=0 & deSummary1[,3]!=0)

# get what these genes are doing and save them to a file
commonGenes.KOR <- getBM(attributes = c('ensembl_gene_id', 'external_gene_name', 'description', "interpro","interpro_description"), mart = ensembl.mart.90,values=names(de.common.KOR), filters="ensembl_gene_id")
write.table(de.common.KOR, file=paste0(outputdir,"allCommonGenes_KOR_dupcor.txt"))
# # save the common gene names 
de.common.KOR=voomNoNormDupEfit$genes[names(de.common.KOR),]

# now plot the common genes to see if they're being regulated in the same direction
pdf(paste0(edaoutput,"logFC_commonKORgenes_dupCor.pdf"))
        ggplot(allGenes[names(deCommonKOR05),], aes(x=logFC.SMB.KOR, y=logFC.MTW.KOR)) +
            geom_point(alpha=0.5, size=0.7) + 
            geom_hline(yintercept = 0, linetype=2, colour="grey60") +
            geom_vline(xintercept = 0, linetype=2, colour="grey60") +
            geom_abline(slope = 1, intercept=0, colour="grey60", linetype=2)
            theme_bw() + 
            labs(title="", y="log2FC Sumba-Korowai", x="log2FC Mentawai-Korowai") + 
            theme(legend.title=element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
            guides(fill=F)
dev.off()